import Foundation
import GRDB

/// An insight generated by the analysis system.
struct Insight: Codable, FetchableRecord, PersistableRecord, Identifiable {
    static let databaseTableName = "insights"

    var id: String
    var createdAt: Date
    var type: String               // anomaly / pattern / milestone / daily / weekly
    var title: String
    var content: String
    var relatedLayers: [Int]       // JSON array in SQLite
    var notified: Bool

    init(
        id: String = UUID().uuidString,
        createdAt: Date = .now,
        type: String,
        title: String,
        content: String,
        relatedLayers: [Int] = [],
        notified: Bool = false
    ) {
        self.id = id
        self.createdAt = createdAt
        self.type = type
        self.title = title
        self.content = content
        self.relatedLayers = relatedLayers
        self.notified = notified
    }

    enum Columns: String, ColumnExpression {
        case id, createdAt, type, title, content, relatedLayers, notified
    }

    enum CodingKeys: String, CodingKey {
        case id, createdAt, type, title, content, relatedLayers, notified
    }

    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        id = try c.decode(String.self, forKey: .id)
        createdAt = try c.decode(Date.self, forKey: .createdAt)
        type = try c.decode(String.self, forKey: .type)
        title = try c.decode(String.self, forKey: .title)
        content = try c.decode(String.self, forKey: .content)
        notified = try c.decode(Bool.self, forKey: .notified)

        let layersStr = try c.decode(String.self, forKey: .relatedLayers)
        if let data = layersStr.data(using: .utf8),
           let decoded = try? JSONDecoder().decode([Int].self, from: data) {
            relatedLayers = decoded
        } else {
            relatedLayers = []
        }
    }

    func encode(to encoder: Encoder) throws {
        var c = encoder.container(keyedBy: CodingKeys.self)
        try c.encode(id, forKey: .id)
        try c.encode(createdAt, forKey: .createdAt)
        try c.encode(type, forKey: .type)
        try c.encode(title, forKey: .title)
        try c.encode(content, forKey: .content)
        try c.encode(notified, forKey: .notified)

        let data = try JSONEncoder().encode(relatedLayers)
        try c.encode(String(data: data, encoding: .utf8) ?? "[]", forKey: .relatedLayers)
    }
}
